### ISSUE TITLE
Change format of roster.json to read from direct export of PokerMavens

### ISSUE THREAD

**Issue by cchervitz** [yellowtongue/process-log-mavens#6]
PokerMavens has an option to Export "Account names & emails" to a file. This should be the format that the roster file directly uses. I know JSON is far easier to parse, and an argument could be made that PokerMavens should just update its export routine to produce a JSON file, but for now, I think this might be the faster route.

**Comment by yellowtongue** [comment]
That's a good thought. The JSON was expedient as (1) it was the internal storage model already, (2) using the json.load command coupled with this established format meant almost no coding to process this input. 

There is also a third element in that by using JSON the data is extensible, Already there is more there in being able to use a friendly name rather than screen name when addressing the player. If that name is available, it will be used in the CSV output. 

All that said, it would be convenient to be able to reference this natural output from Poker Mavens. 

This probably gets done.

**Comment by yellowtongue** [comment]
Done. Will update the Wiki with this information.
